{{- if and (eq (include "opensearch.enableDisasterRecovery" .) "true") .Values.global.disasterRecovery.serviceExport.enabled }}
{{- if not .Values.global.disasterRecovery.serviceExport.region }}
{{ fail "Google Cloud Region should be specified in parameter 'global.disasterRecovery.serviceExport.region' when deployed with enabled ServiceExport." }}
{{- end }}
kind: ServiceExport
apiVersion: net.gke.io/v1
metadata:
  name: {{ template "opensearch.fullname" . }}-{{.Values.global.disasterRecovery.serviceExport.region}}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opensearch-service.defaultLabels" . | nindent 4 }}
{{- end }}