//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Curator) DeepCopyInto(out *Curator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Curator.
func (in *Curator) DeepCopy() *Curator {
	if in == nil {
		return nil
	}
	out := new(Curator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dashboards) DeepCopyInto(out *Dashboards) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dashboards.
func (in *Dashboards) DeepCopy() *Dashboards {
	if in == nil {
		return nil
	}
	out := new(Dashboards)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DbaasAdapter) DeepCopyInto(out *DbaasAdapter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DbaasAdapter.
func (in *DbaasAdapter) DeepCopy() *DbaasAdapter {
	if in == nil {
		return nil
	}
	out := new(DbaasAdapter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterRecovery) DeepCopyInto(out *DisasterRecovery) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterRecovery.
func (in *DisasterRecovery) DeepCopy() *DisasterRecovery {
	if in == nil {
		return nil
	}
	out := new(DisasterRecovery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DisasterRecoveryStatus) DeepCopyInto(out *DisasterRecoveryStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DisasterRecoveryStatus.
func (in *DisasterRecoveryStatus) DeepCopy() *DisasterRecoveryStatus {
	if in == nil {
		return nil
	}
	out := new(DisasterRecoveryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchDbaasAdapter) DeepCopyInto(out *ElasticsearchDbaasAdapter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchDbaasAdapter.
func (in *ElasticsearchDbaasAdapter) DeepCopy() *ElasticsearchDbaasAdapter {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchDbaasAdapter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalOpenSearch) DeepCopyInto(out *ExternalOpenSearch) {
	*out = *in
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalOpenSearch.
func (in *ExternalOpenSearch) DeepCopy() *ExternalOpenSearch {
	if in == nil {
		return nil
	}
	out := new(ExternalOpenSearch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Monitoring) DeepCopyInto(out *Monitoring) {
	*out = *in
	if in.SlowQueries != nil {
		in, out := &in.SlowQueries, &out.SlowQueries
		*out = new(SlowQueries)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Monitoring.
func (in *Monitoring) DeepCopy() *Monitoring {
	if in == nil {
		return nil
	}
	out := new(Monitoring)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenSearch) DeepCopyInto(out *OpenSearch) {
	*out = *in
	if in.Snapshots != nil {
		in, out := &in.Snapshots, &out.Snapshots
		*out = new(Snapshots)
		(*in).DeepCopyInto(*out)
	}
	if in.DisabledRestCategories != nil {
		in, out := &in.DisabledRestCategories, &out.DisabledRestCategories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenSearch.
func (in *OpenSearch) DeepCopy() *OpenSearch {
	if in == nil {
		return nil
	}
	out := new(OpenSearch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenSearchService) DeepCopyInto(out *OpenSearchService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenSearchService.
func (in *OpenSearchService) DeepCopy() *OpenSearchService {
	if in == nil {
		return nil
	}
	out := new(OpenSearchService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenSearchService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenSearchServiceList) DeepCopyInto(out *OpenSearchServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpenSearchService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenSearchServiceList.
func (in *OpenSearchServiceList) DeepCopy() *OpenSearchServiceList {
	if in == nil {
		return nil
	}
	out := new(OpenSearchServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpenSearchServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenSearchServiceSpec) DeepCopyInto(out *OpenSearchServiceSpec) {
	*out = *in
	if in.OpenSearch != nil {
		in, out := &in.OpenSearch, &out.OpenSearch
		*out = new(OpenSearch)
		(*in).DeepCopyInto(*out)
	}
	if in.ExternalOpenSearch != nil {
		in, out := &in.ExternalOpenSearch, &out.ExternalOpenSearch
		*out = new(ExternalOpenSearch)
		(*in).DeepCopyInto(*out)
	}
	if in.Dashboards != nil {
		in, out := &in.Dashboards, &out.Dashboards
		*out = new(Dashboards)
		**out = **in
	}
	if in.Monitoring != nil {
		in, out := &in.Monitoring, &out.Monitoring
		*out = new(Monitoring)
		(*in).DeepCopyInto(*out)
	}
	if in.DbaasAdapter != nil {
		in, out := &in.DbaasAdapter, &out.DbaasAdapter
		*out = new(DbaasAdapter)
		**out = **in
	}
	if in.ElasticsearchDbaasAdapter != nil {
		in, out := &in.ElasticsearchDbaasAdapter, &out.ElasticsearchDbaasAdapter
		*out = new(ElasticsearchDbaasAdapter)
		**out = **in
	}
	if in.Curator != nil {
		in, out := &in.Curator, &out.Curator
		*out = new(Curator)
		**out = **in
	}
	if in.DisasterRecovery != nil {
		in, out := &in.DisasterRecovery, &out.DisasterRecovery
		*out = new(DisasterRecovery)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenSearchServiceSpec.
func (in *OpenSearchServiceSpec) DeepCopy() *OpenSearchServiceSpec {
	if in == nil {
		return nil
	}
	out := new(OpenSearchServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenSearchServiceStatus) DeepCopyInto(out *OpenSearchServiceStatus) {
	*out = *in
	out.DisasterRecoveryStatus = in.DisasterRecoveryStatus
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]StatusCondition, len(*in))
		copy(*out, *in)
	}
	in.RollingUpdateStatus.DeepCopyInto(&out.RollingUpdateStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenSearchServiceStatus.
func (in *OpenSearchServiceStatus) DeepCopy() *OpenSearchServiceStatus {
	if in == nil {
		return nil
	}
	out := new(OpenSearchServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollingUpdateStatus) DeepCopyInto(out *RollingUpdateStatus) {
	*out = *in
	if in.StatefulSetStatuses != nil {
		in, out := &in.StatefulSetStatuses, &out.StatefulSetStatuses
		*out = make([]StatefulSetStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollingUpdateStatus.
func (in *RollingUpdateStatus) DeepCopy() *RollingUpdateStatus {
	if in == nil {
		return nil
	}
	out := new(RollingUpdateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3) DeepCopyInto(out *S3) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3.
func (in *S3) DeepCopy() *S3 {
	if in == nil {
		return nil
	}
	out := new(S3)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlowQueries) DeepCopyInto(out *SlowQueries) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlowQueries.
func (in *SlowQueries) DeepCopy() *SlowQueries {
	if in == nil {
		return nil
	}
	out := new(SlowQueries)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Snapshots) DeepCopyInto(out *Snapshots) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Snapshots.
func (in *Snapshots) DeepCopy() *Snapshots {
	if in == nil {
		return nil
	}
	out := new(Snapshots)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatefulSetStatus) DeepCopyInto(out *StatefulSetStatus) {
	*out = *in
	if in.UpdatedReplicas != nil {
		in, out := &in.UpdatedReplicas, &out.UpdatedReplicas
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatefulSetStatus.
func (in *StatefulSetStatus) DeepCopy() *StatefulSetStatus {
	if in == nil {
		return nil
	}
	out := new(StatefulSetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusCondition) DeepCopyInto(out *StatusCondition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusCondition.
func (in *StatusCondition) DeepCopy() *StatusCondition {
	if in == nil {
		return nil
	}
	out := new(StatusCondition)
	in.DeepCopyInto(out)
	return out
}
