{{- if and .Values.global.externalOpensearch.enabled (or (not .Values.global.externalOpensearch.url) (not .Values.global.externalOpensearch.username) (not .Values.global.externalOpensearch.password)) }}
  {{- fail "If external OpenSearch is used, the following fields should be filled: `global.externalOpensearch.url`, `global.externalOpensearch.username`, `global.externalOpensearch.password`." }}
{{- end }}
{{- if and .Values.deployDescriptor .Values.dockerOpensearch (ne (.Values.DEPLOY_W_HELM | toString) "true") }}
  {{- fail "OpenSearch requires `DEPLOY_W_HELM` parameter to be set to `true` for App Deployer" }}
{{- end }}
apiVersion: qubership.org/v1
kind: OpenSearchService
metadata:
  name: {{ template "opensearch.fullname" . }}
  labels:
    app.kubernetes.io/processed-by-operator: {{ template "opensearch.fullname" . }}-service-operator
    {{- include "opensearch-service.defaultLabels" . | nindent 4 }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    name: {{ template "opensearch.fullname" . }}
    component: opensearch-service
spec:
  {{- if and .Values.global.externalOpensearch.enabled .Values.global.externalOpensearch.applyConfig }}
  externalOpenSearch:
    url: "{{ .Values.global.externalOpensearch.url }}"
    config:
    {{- with .Values.global.externalOpensearch.config }}
      {{- toYaml . | nindent 6 -}}
    {{- end }}
  {{- end }}
  {{- if not .Values.global.externalOpensearch.enabled }}
  opensearch:
    dedicatedClientPod: {{ .Values.opensearch.client.dedicatedPod.enabled }}
    dedicatedDataPod: {{ and .Values.opensearch.data.dedicatedPod.enabled .Values.opensearch.data.enabled }}
    {{- if (ne (.Values.opensearch.audit.disabledRestCategories | toString) "<nil>") }}
    disabledRestCategories: {{ .Values.opensearch.audit.disabledRestCategories  }}
    {{- end }}
    compatibilityModeEnabled: {{ .Values.opensearch.compatibilityModeEnabled }}
    rollingUpdate: {{ .Values.opensearch.rollingUpdate }}
    readinessTimeout: {{ .Values.opensearch.readinessTimeout | default "800s" }}
    {{- if .Values.opensearch.rollingUpdate }}
    statefulSetNames: "{{ trim (include "opensearch.statefulsetNames" .) }}"
    {{ end }}
    {{- if .Values.opensearch.snapshots.enabled }}
    snapshots:
      repositoryName: {{ coalesce .Values.opensearch.snapshots.repositoryName .Values.curator.snapshotRepositoryName | default "snapshots" }}
      {{- if .Values.opensearch.snapshots.s3.enabled }}
      s3:
        enabled: {{ .Values.opensearch.snapshots.s3.enabled }}
        {{- if .Values.opensearch.snapshots.s3.gcs.secretName }}
        gcsEnabled: true
        {{- end }}
        pathStyleAccess: {{ .Values.opensearch.snapshots.s3.pathStyleAccess }}
        url: {{ default "" .Values.opensearch.snapshots.s3.url | quote  }}
        bucket: {{ default "" .Values.opensearch.snapshots.s3.bucket | quote }}
        basePath: {{ default "" .Values.opensearch.snapshots.s3.basePath | quote }}
        region: {{ default "default" .Values.opensearch.snapshots.s3.region | quote }}
        secretName: {{ template "opensearch.fullname" . }}-s3-secret
      {{- end }}
    {{- end }}
    {{- if and .Values.opensearch.securityConfig.config.securityConfigSecret .Values.opensearch.securityConfig.config.data }}
    securityConfigurationName: {{ .Values.opensearch.securityConfig.config.securityConfigSecret }}
    {{- else }}
    securityConfigurationName: {{ template "opensearch.fullname" . }}-security-configuration
    {{- end }}
  {{ end }}
  {{- if .Values.dashboards.enabled }}
  dashboards:
    name: {{ template "opensearch.fullname" . }}-dashboards
    {{- if .Values.dashboards.config }}
    secretName: {{ template "opensearch.fullname" . }}-dashboards-config
    {{- end }}
  {{- end }}
  {{- if (eq (include "monitoring.enabled" .) "true") }}
  monitoring:
    name: {{ template "opensearch.fullname" . }}-monitoring
    {{- if eq .Values.monitoring.monitoringType "influxdb" }}
    secretName: {{ template "opensearch.fullname" . }}-monitoring-secret
    {{- end }}
    {{- if and (not .Values.global.externalOpensearch.enabled) .Values.monitoring.slowQueries.enabled }}
    slowQueries:
      indicesPattern: "{{ .Values.monitoring.slowQueries.indicesPattern | default "*" }}"
      minSeconds: {{ .Values.monitoring.slowQueries.minSeconds }}
    {{- end }}
  {{- end }}
  {{- if eq (include "dbaas.enabled" .) "true" }}
  dbaasAdapter:
    name: {{ template "dbaas-adapter.name" . }}
    secretName: {{ template "dbaas-adapter.name" . }}-secret
    {{- if (eq (include "opensearch.enableDisasterRecovery" .) "true") }}
    adapterAddress: {{ .Values.dbaasAdapter.dbaasAdapterAddress | default (include "dbaas-adapter.address" .) }}
    aggregatorAddress: {{ include "dbaas.registrationUrl" . | default (printf "%s://dbaas-aggregator.dbaas:%s" (include "dbaas-adapter.protocol" .) (include "dbaas-adapter.port" .)) }}
    physicalDatabaseIdentifier: {{ .Values.dbaasAdapter.dbaasAggregatorPhysicalDatabaseIdentifier | default .Release.Namespace }}
    {{- end }}
  {{- end }}
  {{- if .Values.curator.enabled }}
  curator:
    name: {{ template "opensearch.fullname" . }}-curator
    secretName: {{ template "opensearch.fullname" . }}-curator-secret
  {{- end }}
  {{- if (eq (include "opensearch.enableDisasterRecovery" .) "true") }}
  disasterRecovery:
    configMapName: {{ template "opensearch.fullname" . }}-replication-configuration
    mode: {{ .Values.global.disasterRecovery.mode }}
    noWait: true
    replicationWatcherEnabled: {{ .Values.global.disasterRecovery.replicationWatcherEnabled }}
    replicationWatcherInterval: {{ .Values.global.disasterRecovery.replicationWatcherIntervalSeconds }}
  {{- end }}
