{{- if (eq (include "monitoring.enabled" .) "true") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ include "opensearch.labels.standard" . | indent 4 }}
    name: {{ template "opensearch.fullname" . }}-monitoring
    {{- include "opensearch-service.defaultLabels" . | nindent 4 }}
    app.kubernetes.io/name: {{ template "opensearch.fullname" . }}-monitoring
    app.kubernetes.io/instance: {{ cat (printf "%s-monitoring"  (include "opensearch.fullname" .)) .Values.DELIMITER .Release.Namespace | nospace | trunc 63 }}
    app.kubernetes.io/technology: python
    component: opensearch-monitoring
  name: {{ template "opensearch.fullname" . }}-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
{{ include "opensearch.labels.selector" . | indent 6 }}
      component: opensearch-monitoring
      name: {{ template "opensearch.fullname" . }}-monitoring
  template:
    metadata:
      labels:
{{- with .Values.global.customLabels }}
  {{- toYaml . | nindent 8 -}}
{{- end }}
{{- with .Values.monitoring.customLabels }}
  {{- toYaml . | nindent 8 -}}
{{- end }}
{{ include "opensearch.labels.standard" . | indent 8 }}
        component: opensearch-monitoring
        name: {{ template "opensearch.fullname" . }}-monitoring
        app.kubernetes.io/name: {{ template "opensearch.fullname" . }}-monitoring
      annotations:
        {{/* This forces a restart if the secret or config has changed */}}
        checksum/config: {{ include (print .Template.BasePath "/monitoring/configuration.yaml") . | sha256sum | trunc 63 }}
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml .Values.global.imagePullSecrets | indent 8 }}
      {{- end }}
      serviceAccountName: {{ template "opensearch.fullname" . }}-monitoring
      containers:
        - env:
            - name: OS_PROJECT
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.namespace"
            - name: ELASTICSEARCH_HOST
              value: {{ default (printf "%s-internal" (include "opensearch.fullname" .)) (.Values.global.externalOpensearch.enabled | ternary (include "external.opensearch-host" .) .Values.monitoring.opensearchHost) }}
            - name: ELASTICSEARCH_PORT
              value: "{{ default 9200 (.Values.global.externalOpensearch.enabled | ternary (include "external.opensearch-port" .) .Values.monitoring.opensearchPort) }}"
            - name: ELASTICSEARCH_DBAAS_ADAPTER_HOST
              value: {{ .Values.monitoring.opensearchDbaasAdapterHost | default (include "dbaas-adapter.name" .) }}
            - name: ELASTICSEARCH_DBAAS_ADAPTER_PORT
              value: "{{ .Values.monitoring.opensearchDbaasAdapterPort | default 8080 }}"
            - name: ELASTICSEARCH_TOTAL_NODES_COUNT
              value: "{{ include "opensearch.nodes.count" . }}"
            - name: ELASTICSEARCH_DATA_NODES_COUNT
              value: "{{ include "opensearch.dataNodes.count" . }}"
            - name: ELASTICSEARCH_EXEC_PLUGIN_TIMEOUT
              value: {{ .Values.monitoring.opensearchExecPluginTimeout | default "15s" }}
            - name: ELASTICSEARCH_PROTOCOL
              {{ if or (eq (include "external.tlsEnabled" .) "true") (eq (include "opensearch.tlsEnabled" .) "true") }}
              value: "https"
              {{ else }}
              value: "http"
              {{ end }}
          {{- if (eq .Values.monitoring.monitoringType "influxdb") }}
            - name: SM_DB_HOST
              value: {{ .Values.monitoring.smDbHost }}
            - name: SM_DB_NAME
              value: {{ .Values.monitoring.smDbName }}
            - name: SM_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ template "opensearch.fullname" . }}-monitoring-secret
                  key: sm-db-username
            - name: SM_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "opensearch.fullname" . }}-monitoring-secret
                  key: sm-db-password
          {{- end }}
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: {{ template "opensearch.fullname" . }}-secret
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: {{ template "opensearch.fullname" . }}-secret
            {{- if and (not .Values.global.externalOpensearch.enabled) .Values.monitoring.slowQueries.enabled }}
            - name: SLOW_QUERIES_TOP_NUMBER
              value: {{ default 10 .Values.monitoring.slowQueries.topNumber | quote }}
            - name: PROCESSING_INTERVAL_MINUTES
              value: {{ default 5 .Values.monitoring.slowQueries.processingIntervalMinutes | quote }}
            {{- end }}
          image: {{ template "monitoring.image" . }}
          imagePullPolicy: {{ .Values.monitoring.imagePullPolicy | default "Always" | quote }}
          resources:
{{ toYaml .Values.monitoring.resources | indent 12 }}
          securityContext:
            {{- include "opensearch-service.globalContainerSecurityContext" . | nindent 12 }}
          name: {{ template "opensearch.fullname" . }}-monitoring
          volumeMounts:
            - mountPath: "/etc/telegraf"
              name: config
            {{- if eq (include "opensearch.tlsEnabled" .) "true" }}
            - mountPath: /trusted-certs/root-ca.pem
              name: opensearch-certs
              subPath: {{ template "opensearch.root-ca-path" . }}
            {{- end }}
          ports:
            - protocol: TCP
              containerPort: 8125
            - protocol: TCP
              containerPort: 8094
            - protocol: UDP
              containerPort: 8092
          {{- if (ne .Values.monitoring.monitoringType "influxdb") }}
            - protocol: TCP
              containerPort: 8096
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ template "opensearch.fullname" . }}-monitoring-configuration
            items:
              - key: config
                path: telegraf.conf
        {{- if eq (include "opensearch.tlsEnabled" .) "true" }}
        - name: opensearch-certs
          secret:
            secretName: {{ template "opensearch.rest-cert-secret-name" . }}
        {{- end }}
      {{- if .Values.monitoring.priorityClassName }}
      priorityClassName: {{ .Values.monitoring.priorityClassName | quote }}
      {{- end }}
    {{- with .Values.monitoring.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
      securityContext:
        {{- include "opensearch-service.globalPodSecurityContext" . | nindent 8 }}
        {{- with .Values.monitoring.securityContext }}
          {{- toYaml . | nindent 8 -}}
        {{- end }}
    {{- with .Values.monitoring.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.monitoring.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{ end }}
