{{- if (eq (include "monitoring.enabled" .) "true") }}
apiVersion: v1
kind: Service
metadata:
  labels:
{{ include "opensearch.labels.standard" . | indent 4 }}
{{ include "opensearch-service.defaultLabels" . | indent 4 }}
    name: {{ template "opensearch.fullname" . }}-monitoring
    app.kubernetes.io/name: {{ template "opensearch.fullname" . }}-monitoring
    component: opensearch-monitoring
  name: {{ template "opensearch.fullname" . }}-monitoring
spec:
  ports:
    - name: opensearch-monitoring-statsd
      port: 8125
      protocol: TCP
    - name: opensearch-monitoring-tcp
      port: 8094
      protocol: TCP
    - name: opensearch-monitoring-udp
      port: 8092
      protocol: UDP
    {{- if (ne .Values.monitoring.monitoringType "influxdb") }}
    - name: prometheus-cli
      port: 8096
      protocol: TCP
    {{- end }}
  selector:
    name: {{ template "opensearch.fullname" . }}-monitoring
    component: opensearch-monitoring
{{- end }}