{{- if not .Values.global.externalOpensearch.enabled }}
{{- if and .Values.opensearch.data.podDisruptionBudget.enabled .Values.opensearch.data.enabled .Values.opensearch.data.dedicatedPod.enabled }}
{{- if .Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" }}
apiVersion: policy/v1
{{- else }}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ template "opensearch.fullname" . }}-data-pdb
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "opensearch.labels.standard" . | indent 4 }}
{{ include "opensearch-service.defaultLabels" . | indent 4 }}
spec:
{{- if .Values.opensearch.data.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.opensearch.data.podDisruptionBudget.minAvailable }}
{{- end }}
{{- if .Values.opensearch.data.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.opensearch.data.podDisruptionBudget.maxUnavailable }}
{{- end }}
  selector:
    matchLabels:
      app: {{ template "opensearch.fullname" . }}
      role: data
{{- end }}
{{- end }}
