{{- if and (not (and (include "opensearch.username" .) (include "opensearch.password" .))) (not .Values.global.externalOpensearch.enabled) }}
{{ fail "credentials for OpenSearch ('.Values.opensearch.securityConfig.authc.basic.username' and '.Values.opensearch.securityConfig.authc.basic.password') must be specified" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "opensearch.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    automation.infra/secret-change: "true"
{{ include "opensearch.labels.standard" . | indent 4 }}
{{ include "opensearch-service.defaultLabels" . | indent 4 }}
type: Opaque
stringData:
  {{- if not .Values.global.externalOpensearch.enabled }}
  username: "{{ (include "opensearch.username" .) }}"
  password: "{{ (include "opensearch.password" .) }}"
  {{- else }}
  username: "{{ .Values.global.externalOpensearch.username }}"
  password: "{{ .Values.global.externalOpensearch.password }}"
  {{- end }}
