{{- if .Values.statusProvisioner.enabled }}
# status-provisioner job provides status about cluster state
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "opensearch.fullname" . }}-status-provisioner
  labels:
    name: {{ template "opensearch.fullname" . }}-status-provisioner
    {{- include "opensearch-service.defaultLabels" . | nindent 4 }}
    app.kubernetes.io/name: {{ template "opensearch.fullname" . }}-status-provisioner
    app.kubernetes.io/instance: {{ cat (printf "%s-status-provisioner"  (include "opensearch.fullname" .)) .Values.DELIMITER .Release.Namespace | nospace | trunc 63 }}
    app.kubernetes.io/technology: python
  annotations:
    "argocd.argoproj.io/hook": PostSync
    "argocd.argoproj.io/sync-wave": "1"
    "argocd.argoproj.io/hook-delete-policy": HookSucceeded,BeforeHookCreation
spec:
  {{- if or (gt .Capabilities.KubeVersion.Major "1") (ge .Capabilities.KubeVersion.Minor "12") }}
  ttlSecondsAfterFinished: {{ .Values.statusProvisioner.lifetimeAfterCompletion | default 600 }}
  {{- end }}
  template:
    metadata:
      name: {{ template "opensearch.fullname" . }}-status-provisioner
      labels:
{{- with .Values.global.customLabels }}
  {{- toYaml . | nindent 8 -}}
{{- end }}
{{- with .Values.statusProvisioner.customLabels }}
  {{- toYaml . | nindent 8 -}}
{{- end }}
        component: status-provisioner
        name: {{ template "opensearch.fullname" . }}-status-provisioner
        app.kubernetes.io/name: {{ template "opensearch.fullname" . }}-status-provisioner
{{ include "opensearch.labels.standard" . | nindent 8 }}
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml .Values.global.imagePullSecrets | indent 8 }}
      {{- end }}
      restartPolicy: Never
      serviceAccountName: {{ template "opensearch.fullname" . }}-status-provisioner
      securityContext:
        {{- include "opensearch-service.globalPodSecurityContext" . | nindent 8 }}
        {{- with .Values.statusProvisioner.securityContext }}
          {{- toYaml . | nindent 8 -}}
        {{- end }}
      containers:
        - name: status-provisioner
          image: {{ template "deployment-status-provisioner.image" . }}
          imagePullPolicy: "Always"
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MONITORED_RESOURCES
              value: "{{ include "opensearch.monitoredResources" . }}"
            - name: RESOURCE_TO_SET_STATUS
              value: {{ printf "batch v1 jobs %s-status-provisioner" (include "opensearch.fullname" .) }}
            - name: CONDITION_REASON
              value: "OpenSearchServiceReadinessStatus"
            - name: POD_READINESS_TIMEOUT
              value: "{{ .Values.statusProvisioner.podReadinessTimeout | default 800 }}"
            - name: MONITORED_CUSTOM_RESOURCES
              value: {{ printf "qubership.org v1 opensearchservices %s $.status.conditions[?(@.reason=='ReconcileCycleStatus')].type Successful" (include "opensearch.fullname" .) }}
            - name: CR_PROCESSING_TIMEOUT
              value: "{{ .Values.statusProvisioner.crProcessingTimeout | default 600 }}"
          {{- if and .Values.integrationTests.enabled .Values.integrationTests.statusWritingEnabled (not (or (eq .Values.global.disasterRecovery.mode "standby") (eq .Values.global.disasterRecovery.mode "disabled"))) }}
            - name: INTEGRATION_TESTS_RESOURCE
              value: {{ printf "apps v1 deployments %s-integration-tests" (include "opensearch.fullname" .) }}
            - name: INTEGRATION_TESTS_CONDITION_REASON
              value: "IntegrationTestsExecutionStatus"
            - name: INTEGRATION_TESTS_SUCCESSFUL_CONDITION_TYPE
              value: "Ready"
            - name: INTEGRATION_TESTS_TIMEOUT
              value: "{{ .Values.statusProvisioner.integrationTestsTimeout | default 300 }}"
          {{- end }}
          resources:
            requests:
              cpu: {{ default "50m" .Values.statusProvisioner.resources.requests.cpu }}
              memory: {{ default "50Mi" .Values.statusProvisioner.resources.requests.memory }}
            limits:
              cpu: {{ default "100m" .Values.statusProvisioner.resources.limits.cpu }}
              memory: {{ default "100Mi" .Values.statusProvisioner.resources.limits.memory }}
          securityContext:
            {{- include "opensearch-service.globalContainerSecurityContext" . | nindent 12 }}
{{- end }}