{{- if eq (include "opensearch-status-provisioner.cleanupEnabled" .) "true" }}
# status-provisioner-cleanup deletes previous status-provisioner job if it exists
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "opensearch.fullname" . }}-status-provisioner-cleanup
  labels:
    name: {{ template "opensearch.fullname" . }}-status-provisioner-cleanup
    {{- include "opensearch-service.defaultLabels" . | nindent 4 }}
    app.kubernetes.io/name: {{ template "opensearch.fullname" . }}-status-provisioner-cleanup
    app.kubernetes.io/instance: {{ cat (printf "%s-status-provisioner-cleanup"  (include "opensearch.fullname" .)) .Values.DELIMITER .Release.Namespace | nospace | trunc 63 }}
    app.kubernetes.io/technology: python
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    metadata:
      name: {{ template "opensearch.fullname" . }}-status-provisioner-cleanup
      labels:
{{- with .Values.global.customLabels }}
  {{- toYaml . | nindent 8 -}}
{{- end }}
{{- with .Values.statusProvisioner.customLabels }}
  {{- toYaml . | nindent 8 -}}
{{- end }}
        component: status-provisioner-cleanup
        name: {{ template "opensearch.fullname" . }}-status-provisioner-cleanup
        app.kubernetes.io/name: {{ template "opensearch.fullname" . }}-status-provisioner-cleanup
{{ include "opensearch.labels.standard" . | nindent 8 }}
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
      {{ toYaml .Values.global.imagePullSecrets | indent 8 }}
      {{- end }}
      restartPolicy: Never
      serviceAccountName: {{ template "opensearch.fullname" . }}-status-provisioner-cleanup
      securityContext:
        {{- include "opensearch-service.globalPodSecurityContext" . | nindent 8 }}
        {{- with .Values.statusProvisioner.securityContext }}
          {{- toYaml . | nindent 8 -}}
        {{- end }}
      containers:
        - name: status-provisioner-cleanup
          image: {{ template "deployment-status-provisioner.image" . }}
          command:
            - "/bin/bash"
            - "-c"
            - kubectl delete job {{ template "opensearch.fullname" . }}-status-provisioner --ignore-not-found=true
          resources:
            requests:
              cpu: {{ default "50m" .Values.statusProvisioner.resources.requests.cpu }}
              memory: {{ default "50Mi" .Values.statusProvisioner.resources.requests.memory }}
            limits:
              cpu: {{ default "100m" .Values.statusProvisioner.resources.limits.cpu }}
              memory: {{ default "100Mi" .Values.statusProvisioner.resources.limits.memory }}
          securityContext:
            {{- include "opensearch-service.globalContainerSecurityContext" . | nindent 12 }}
{{- end }}